# Coordinates are FRACTIONS OF THE FULL IMAGE (0..1).
# crop may extend outside 0..1 to leave a blank margin for the callout badges.
SIZES = {
    "ipad-00-stopped.png":     (1640, 2360),
    "ipad-01-main.png":        (1640, 2360),
    "ipad-02-device-card.png": (1640, 2360),
    "ipad-03-controls.png":    (1640, 2360),
    "ipad-04-playing.png":     (1640, 2360),
    "ipad-05-pause-stop.png":  (1640, 2360),
    "ipad-06-paused.png":      (1640, 2360),
    "ios-02-transfer.png":     (1206, 2622),
    "ios-03-transfer-send.png":(1206, 2622),
    "ios-04-log.png":          (1206, 2622),
    "vp-01-main.png":          (2000, 1125),
    "vp-02-settings.png":      (2000, 1125),
    "vp-03-immersive.png":     (2000, 1073),
}

# pad helpers
IPADC = (-0.115, 1.115)   # left/right crop for full-width tablet shots
IL, IR = -0.072, 1.072    # badge lanes for those

FIGURES = {

"server-stopped": dict(
    src="ipad-00-stopped.png", crop=(IPADC[0], 0.0, IPADC[1], 0.70),
    caption="Controller app, server not yet started. Nothing can reach the headsets in this state.",
    callouts=[
        dict(t=(0.061,0.046), b=(IL,0.040), n=1),
        dict(t=(0.106,0.092), b=(IL,0.120), n=2),
        dict(t=(0.499,0.539), b=(IR,0.500), n=3),
        dict(t=(0.499,0.622), b=(IR,0.630), n=4),
    ],
    legend=[
        "<b>Start</b> — the master switch in the navigation bar. The same button becomes <b>Stop</b> once running.",
        "<b>Server Stopped</b> — red dot. While this says Stopped, no headset can connect, no video can be sent, and nothing is discoverable on the network.",
        "<b>No Devices Connected</b> — the headset list is empty. Expected before the server is started.",
        "<b>Start Server</b> — starts the WebSocket server on port <b>8080</b>, the file-transfer server on port <b>8081</b>, and begins advertising the controller so headsets can find it by themselves.",
    ]),

"main-running": dict(
    src="ipad-01-main.png", crop=(IPADC[0], 0.0, IPADC[1], 0.66),
    caption="Controller app with the server running and one headset connected.",
    callouts=[
        dict(t=(0.063,0.046), b=(IL,0.030), n=1),
        dict(t=(0.104,0.092), b=(IL,0.090), n=2),
        dict(t=(0.832,0.092), b=(IR,0.090), n=3),
        dict(t=(0.950,0.092), b=(IR,0.150), n=4),
        dict(t=(0.847,0.046), b=(IR,0.030), n=5),
        dict(t=(0.903,0.046), b=(IR,-0.012), n=6),
        dict(t=(0.960,0.046), b=(IR,-0.054), n=7),
        dict(t=(0.190,0.169), b=(IL,0.165), n=8),
        dict(t=(0.936,0.168), b=(IR,0.210), n=9),
        dict(t=(0.122,0.251), b=(IL,0.250), n=10),
        dict(t=(0.842,0.292), b=(IR,0.290), n=11),
        dict(t=(0.182,0.616), b=(IL,0.600), n=12),
        dict(t=(0.109,0.652), b=(IL,0.660), n=13),
        dict(t=(0.180,0.717), b=(IL,0.720), n=14),
        dict(t=(0.135,0.740), b=(IL,0.780), n=15),
        dict(t=(0.427,0.729), b=(IR,0.729), n=16),
    ],
    legend=[
        "<b>Stop</b> — stops the server. Every headset disconnects immediately.",
        "<b>Server Running</b> — green dot. The only state in which headsets can connect.",
        "<b>Port 8080</b> — the WebSocket control port the headsets talk to.",
        "<b>1 device</b> — how many headsets are connected right now. If this says 0, no headset has found the controller.",
        "<b>Send Videos</b> <span class=\"gl\">&#61;</span> (the box with an arrow leaving it) — opens the transfer sheet used to copy a video onto a headset.",
        "<b>Preview Library</b> (two stacked rectangles) — the library of <b>flat companion videos</b> kept on the tablet. These are never sent to a headset; they exist so the operator can watch along on the tablet. Import them here, then pair one to a headset video by long-pressing its tile.",
        "<b>Activity Log</b> (lines in a box) — the timestamped record of everything the controller did. The first place to look when something behaves unexpectedly.",
        "<b>Vision Pro Connection URL</b> — the address of this controller. Headsets normally find it automatically; this is what you would type by hand if they do not.",
        "<b>Copy</b> — copies that URL to the clipboard.",
        "<b>VIDEOS ON ALL DEVICES</b> — only videos whose <b>filename is identical on every connected headset</b> appear here.",
        "<b>Selection tick</b> — the video that <b>Play on All</b> will use.",
        "<b>Format</b> — how the headsets should interpret the picture (360°, 180°, side-by-side, over-under, flat). Must match the actual video.",
        "<b>Play on All</b> — starts the selected video on every connected headset at the same instant.",
        "<b>Headset card</b> — one card per connected headset, titled with that headset's own device name.",
        "<b>Status badge</b> — Idle / Playing / Paused / Stopped, plus <i>Immersive</i> when the headset has its immersive view open.",
        "<b>Video count and chevron</b> — how many videos this headset holds; tap the chevron to expand the card.",
    ]),

"vp-main": dict(
    src="vp-01-main.png", crop=(0.345, 0.375, 0.655, 0.715),
    caption="The Vision Pro Player window as the wearer sees it. The app must be open on this window for the headset to be controllable.",
    callouts=[
        dict(t=(0.500,0.443), b=(0.368,0.415), n=1),
        dict(t=(0.560,0.448), b=(0.632,0.408), n=2),
        dict(t=(0.500,0.481), b=(0.368,0.470), n=3),
        dict(t=(0.500,0.517), b=(0.368,0.525), n=4),
        dict(t=(0.500,0.546), b=(0.632,0.545), n=5),
        dict(t=(0.500,0.620), b=(0.368,0.615), n=6),
        dict(t=(0.500,0.638), b=(0.632,0.660), n=7),
    ],
    legend=[
        "<b>Device name</b> — which headset this is. Set it per headset so the operator can tell them apart.",
        "<b>Settings</b> — opens the panel in the previous figure.",
        "<b>Connected</b> — green means this headset has a live link to a controller. <b>Disconnected</b> or <b>Connecting…</b> means it does not.",
        "<b>Controller address</b> — the controller this headset is actually talking to. Tap it to open Settings.",
        "<b>Disconnect</b> — drops the link deliberately. Only needed when moving a headset to a different controller.",
        "<b>Playback state</b> — mirrors what the controller shows for this headset.",
        "<b>Current file</b> — the exact file the headset has loaded. Useful when checking that every headset really is on the same video.",
    ]),

"vp-settings": dict(
    src="vp-02-settings.png", crop=(0.345, 0.035, 0.735, 0.735),
    caption="Vision Pro Player → Settings. Everything the headset needs in order to be found and identified.",
    callouts=[
        dict(t=(0.439,0.093), b=(0.368,0.070), n=1),
        dict(t=(0.643,0.093), b=(0.712,0.070), n=2),
        dict(t=(0.494,0.131), b=(0.368,0.130), n=3),
        dict(t=(0.474,0.166), b=(0.368,0.185), n=4),
        dict(t=(0.480,0.218), b=(0.368,0.240), n=5),
        dict(t=(0.645,0.218), b=(0.712,0.215), n=6),
        dict(t=(0.503,0.298), b=(0.712,0.300), n=7),
        dict(t=(0.467,0.371), b=(0.368,0.380), n=8),
        dict(t=(0.451,0.515), b=(0.368,0.520), n=9),
        dict(t=(0.640,0.604), b=(0.712,0.600), n=10),
    ],
    legend=[
        "<b>Cancel</b> — closes Settings without keeping the changes.",
        "<b>Save</b> — keeps them. The device name and chosen controller are remembered until you change them again or delete the app.",
        "<b>iOS Controllers (Auto-Discovery)</b> — controllers the headset can currently see on the network. Built automatically; you type nothing to populate it.",
        "<b>Searching for controllers…</b> — the headset is actively looking. If it never finds anything, the network is blocking discovery.",
        "<b>A discovered controller</b> — its name and the address it is reachable at. Tap a row to use that controller.",
        "<b>Green tick</b> — the controller this headset is connected to right now.",
        "<b>Same-network reminder</b> — headset and controller must be on the same Wi-Fi network. The single most common cause of a headset not appearing.",
        "<b>Manual Server Connection</b> — the fallback. Type the address shown on the controller if auto-discovery cannot work on this network.",
        "<b>Device name</b> — <u>this is how you name a headset</u>. Give each one a distinct, physical name (\"Lobby Headset\", \"Seat 1\"). It appears on the controller card and in the log.",
        "<b>Auto-connect on launch</b> — leave this ON. The headset then reconnects by itself whenever the app opens or the Wi-Fi comes back.",
    ]),

"transfer": dict(
    src="ios-03-transfer-send.png", crop=(-0.155, 0.05, 1.155, 0.75),
    caption="Send Videos — copying a video from the controller onto one headset.",
    callouts=[
        dict(t=(0.145,0.115), b=(-0.095,0.100), n=1),
        dict(t=(0.284,0.200), b=(-0.095,0.190), n=2),
        dict(t=(0.282,0.274), b=(-0.095,0.272), n=3),
        dict(t=(0.716,0.274), b=(1.095,0.272), n=4),
        dict(t=(0.478,0.349), b=(1.095,0.345), n=5),
        dict(t=(0.511,0.403), b=(-0.095,0.400), n=6),
        dict(t=(0.864,0.413), b=(1.095,0.420), n=7),
        dict(t=(0.283,0.521), b=(-0.095,0.520), n=8),
        dict(t=(0.370,0.583), b=(1.095,0.583), n=9),
        dict(t=(0.535,0.911), b=(-0.095,0.905), n=10),
    ],
    legend=[
        "<b>Cancel</b> — closes the sheet. Nothing is sent.",
        "<b>Step 1 — Select Videos</b> — choose the file(s) to copy.",
        "<b>Photos</b> — pick from the tablet's photo library. <b>Warning:</b> Photos does not preserve the original filename — see callout 6.",
        "<b>Files</b> — pick from the Files app, iCloud Drive or a connected drive. <b>This preserves the real filename and is the recommended route.</b>",
        "<b>Hint</b> — Vision Pro / spatial videos often do not appear in Photos at all; use Files for those.",
        "<b>The filename that will be used.</b> Here the video came from Photos and arrived as <code>E736F8EA-2264-47A3-AC24-3F7B…</code> — a meaningless identifier. That exact string becomes the filename on the headset.",
        "<b>Remove</b> — takes this file out of the selection.",
        "<b>Step 2 — Select Device</b> — which headset receives the file. <b>One headset per send</b>; repeat for each.",
        "<b>A headset</b> — its name and how many videos it already holds. Tap to select.",
        "<b>Send</b> — starts the copy over Wi-Fi. Progress appears in the Activity Log; the headset's video list refreshes automatically when it finishes.",
    ]),

"device-card": dict(
    src="ipad-03-controls.png", crop=(-0.145, 0.48, 0.60, 1.0),
    caption="An expanded headset card, with no video selected yet.",
    callouts=[
        dict(t=(0.180,0.630), b=(-0.095,0.560), n=1),
        dict(t=(0.135,0.652), b=(-0.095,0.630), n=2),
        dict(t=(0.130,0.698), b=(-0.095,0.700), n=3),
        dict(t=(0.432,0.698), b=(0.552,0.690), n=4),
        dict(t=(0.238,0.745), b=(0.552,0.750), n=5),
        dict(t=(0.155,0.797), b=(-0.095,0.790), n=6),
        dict(t=(0.146,0.861), b=(-0.095,0.860), n=7),
        dict(t=(0.142,0.924), b=(-0.095,0.930), n=8),
        dict(t=(0.365,0.924), b=(0.552,0.930), n=9),
    ],
    legend=[
        "<b>Headset name</b> — as set on that headset.",
        "<b>Status badge</b> — Idle here: connected but not playing anything.",
        "<b>Local Videos</b> — what is actually stored on <i>this</i> headset.",
        "<b>6 available</b> — the count. If a video you sent is missing, it never arrived; check the Activity Log.",
        "<b>Video tile</b> — tap to select it for this headset. It gets a blue outline when selected.",
        "<b>Delete</b> (trash) — permanently removes that video from the headset. You are asked to confirm first.",
        "<b>Video Format</b> — the per-headset format used by this card's Play button. Set it to match the video you are about to play.",
        "<b>Play</b> — greyed out until a video is selected.",
        "<b>Stop</b> — greyed out because nothing is playing.",
    ]),

"playing": dict(
    src="ipad-05-pause-stop.png", crop=(-0.145, 0.48, 0.60, 1.0),
    caption="The same card while the headset is playing.",
    callouts=[
        dict(t=(0.147,0.535), b=(-0.095,0.520), n=1),
        dict(t=(0.251,0.535), b=(0.552,0.530), n=2),
        dict(t=(0.238,0.629), b=(0.552,0.625), n=3),
        dict(t=(0.146,0.734), b=(-0.095,0.720), n=4),
        dict(t=(0.184,0.774), b=(0.552,0.780), n=5),
        dict(t=(0.101,0.858), b=(-0.095,0.855), n=6),
        dict(t=(0.142,0.924), b=(-0.095,0.930), n=7),
        dict(t=(0.365,0.924), b=(0.552,0.930), n=8),
    ],
    legend=[
        "<b>Playing</b> — green. The headset is rendering the video now.",
        "<b>Immersive</b> — purple. The immersive view is open, so the wearer is inside the video rather than looking at a window.",
        "<b>Blue outline</b> — the video currently selected on this card.",
        "<b>Video Format</b> — what this playback was started with.",
        "<b>No preview video for this one</b> — no flat companion is paired, so the operator cannot watch along. Long-press a video tile to pair one.",
        "<b>Now Playing</b> — the file the headset actually loaded. Check this when verifying that every headset is on the same video.",
        "<b>Pause</b> — freezes the picture at the current position and keeps the immersive view open.",
        "<b>Stop</b> — ends playback, closes the immersive view and returns the wearer to the app window.",
    ]),

"paused": dict(
    src="ipad-06-paused.png", crop=(-0.145, 0.50, 0.60, 1.0),
    caption="After Pause. The button becomes Resume; the immersive view stays open.",
    callouts=[
        dict(t=(0.147,0.535), b=(-0.095,0.540), n=1),
        dict(t=(0.251,0.535), b=(0.552,0.535), n=2),
        dict(t=(0.142,0.924), b=(-0.095,0.930), n=3),
        dict(t=(0.365,0.924), b=(0.552,0.930), n=4),
    ],
    legend=[
        "<b>Paused</b> — orange. The video is held at its current position.",
        "<b>Immersive still lit</b> — the wearer is still inside the immersive view looking at a frozen frame, not dropped back to the window.",
        "<b>Resume</b> — continues from exactly where it paused.",
        "<b>Stop</b> — ends the session instead of resuming.",
    ]),

"log": dict(
    src="ios-04-log.png", crop=(-0.155, 0.05, 1.155, 0.85),
    caption="The Activity Log during a synchronised start. Read it bottom-to-top: it is the sequence the system actually followed.",
    callouts=[
        dict(t=(0.128,0.115), b=(-0.095,0.100), n=1),
        dict(t=(0.868,0.115), b=(1.095,0.100), n=2),
        dict(t=(0.084,0.181), b=(-0.095,0.185), n=3),
        dict(t=(0.543,0.774), b=(1.095,0.790), n=4),
        dict(t=(0.620,0.680), b=(1.095,0.690), n=5),
        dict(t=(0.609,0.588), b=(1.095,0.595), n=6),
        dict(t=(0.543,0.493), b=(1.095,0.500), n=7),
        dict(t=(0.636,0.395), b=(1.095,0.400), n=8),
        dict(t=(0.400,0.302), b=(-0.095,0.300), n=9),
    ],
    legend=[
        "<b>Clear</b> — empties the log. Do this before reproducing a problem so the log holds only the relevant run.",
        "<b>Done</b> — closes the log.",
        "<b>Timestamp</b> — every line is stamped, so you can see how long each step took.",
        "<b>Measuring clock offsets…</b> — before anything plays, the controller measures each headset's clock against its own.",
        "<b>offset 0ms (rtt 2ms, 5 samples)</b> — the result for one headset. A small round-trip time means a healthy network; a large or wildly varying one is the signature of congested or badly-configured Wi-Fi.",
        "<b>Preparing '…' on all devices</b> — each headset is told to open its immersive view and pre-load the file, but <i>not</i> to start.",
        "<b>Ready for sync</b> — that headset reported it is loaded and waiting. Every headset must report this before anything starts.",
        "<b>Sync start scheduled (+1000ms)</b> — the controller picks a moment one second ahead and tells every headset to begin exactly then, each in its own corrected clock.",
        "<b>Playback ended on all devices</b> — the session finished normally.",
    ]),

"immersive": dict(
    src="vp-03-immersive.png", crop=(0.0, 0.0, 1.0, 1.0),
    caption="A frame from inside immersive playback \u2014 one eye's view of a 360\u00b0 scene wrapped around the wearer. The app window is hidden while this is on screen, and the wearer can look anywhere in the sphere.",
    callouts=[], legend=[]),
}
